
package io.spring.guides.gs_producing_web_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CountriesPort", targetNamespace = "http://spring.io/guides/gs-producing-web-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountriesPort {


    /**
     * 
     * @param getUsersRequest
     * @return
     *     returns io.spring.guides.gs_producing_web_service.GetUsersResponse
     */
    @WebMethod
    @WebResult(name = "getUsersResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getUsersResponse")
    public GetUsersResponse getUsers(
        @WebParam(name = "getUsersRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getUsersRequest")
        GetUsersRequest getUsersRequest);

    /**
     * 
     * @param registerUserRequest
     * @return
     *     returns io.spring.guides.gs_producing_web_service.RegisterUserResponse
     */
    @WebMethod
    @WebResult(name = "registerUserResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "registerUserResponse")
    public RegisterUserResponse registerUser(
        @WebParam(name = "registerUserRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "registerUserRequest")
        RegisterUserRequest registerUserRequest);

    /**
     * 
     * @param getCountryRequest
     * @return
     *     returns io.spring.guides.gs_producing_web_service.GetCountryResponse
     */
    @WebMethod
    @WebResult(name = "getCountryResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getCountryResponse")
    public GetCountryResponse getCountry(
        @WebParam(name = "getCountryRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getCountryRequest")
        GetCountryRequest getCountryRequest);

    /**
     * 
     * @param postCountryRequest
     * @return
     *     returns io.spring.guides.gs_producing_web_service.PostCountryResponse
     */
    @WebMethod
    @WebResult(name = "postCountryResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "postCountryResponse")
    public PostCountryResponse postCountry(
        @WebParam(name = "postCountryRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "postCountryRequest")
        PostCountryRequest postCountryRequest);

    /**
     * 
     * @param deleteCountryRequest
     * @return
     *     returns io.spring.guides.gs_producing_web_service.DeleteCountryResponse
     */
    @WebMethod
    @WebResult(name = "deleteCountryResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "deleteCountryResponse")
    public DeleteCountryResponse deleteCountry(
        @WebParam(name = "deleteCountryRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "deleteCountryRequest")
        DeleteCountryRequest deleteCountryRequest);

    /**
     * 
     * @param loginUserRequest
     * @return
     *     returns io.spring.guides.gs_producing_web_service.LoginUserResponse
     */
    @WebMethod
    @WebResult(name = "loginUserResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "loginUserResponse")
    public LoginUserResponse loginUser(
        @WebParam(name = "loginUserRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "loginUserRequest")
        LoginUserRequest loginUserRequest);

    /**
     * 
     * @param logoutUserRequest
     * @return
     *     returns io.spring.guides.gs_producing_web_service.LogoutUserResponse
     */
    @WebMethod
    @WebResult(name = "logoutUserResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "logoutUserResponse")
    public LogoutUserResponse logoutUser(
        @WebParam(name = "logoutUserRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "logoutUserRequest")
        LogoutUserRequest logoutUserRequest);

}
